### ISSUE TITLE
SPONSOR: Remove deleting option for the attachments once the order is initiated

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/csc-workspace-main#140]
Once the order is created and the Sponsor later accesses it to view, the attachments can be downloaded but cannot be deleted.

<img width="1436" alt="Screenshot 2021-08-27 at 12 43 21 PM" src="https://user-images.githubusercontent.com/77613409/131108150-daf7b4ba-daf3-4263-ac08-b3b540806212.png">

**Comment by Mastaleru** [comment]
@klivit it is ok to delete attachments that may mattered in the making the decision that an order should be approved or canceled? I was thinking that an version control may be introduced in the future. Please discuss this with business people. Otherwise a deleted file will be lost forever and no tracking could be made on it.  For example a sponsor added File A with some terms and conditions. CMO accepts its, and after that the Sponsor  delete File A and reupload it with some different terms.

**Comment by Mastaleru** [comment]
The desired behavior already exists

**Comment by Mastaleru** [comment]
the issue still exists. it will be handled in #180
