### ISSUE TITLE
Implement AccordionUIController

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/csc-workspace-main#511]
In order to avoid copy-pasted code from one controller to another.:
should support methods like: 
:toggleAccordionItemHandler
:openFirstAccordion
:closeAccordionItem

it should read the html file where the controller runs and get the accordion items and add event listeners to them automatically:
eg. 

```
this.onTagEvent('order_details_accordion', 'click', (e) => {
      this.toggleAccordionItem('order_details_accordion');
      this.model.accordion.order_details.isOpened = !this.model.accordion.order_details.isOpened;
});

```

**Comment by abhayprasadnovartis** [comment]
I created csc-services\controllers\impl\helpers\AccordionController.js file. Do I need to move toggleAccordionItemHandler, openFirstAccordion from csc-services\controllers\impl\helpers\ViewShipmentBaseController.js into this new file?

Since ViewShipmentBaseController is itself a base controller will it inherit AccordionController?

**Comment by abhayprasadnovartis** [comment]
Created PR for this

**Comment by Mastaleru** [comment]
Reopened -  not fully implemented
